# Generated by Django 3.0.5 on 2020-10-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201013_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default='2020-10-15T17:03:05+09:00'),
        ),
    ]
