# Generated by Django 3.0.5 on 2020-10-19 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='image',
        ),
    ]
