# Generated by Django 3.0.5 on 2020-11-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201020_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='D:\\school\\대회 및 프로젝트\\CoCo\\media\\default_image.jpeg', null=True, upload_to=''),
        ),
    ]
