# Generated by Django 3.0.5 on 2020-11-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201105_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token_expires_at',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
