# Generated by Django 3.0.5 on 2020-09-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
