# Generated by Django 3.0.5 on 2020-10-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_comments_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_cnt',
        ),
    ]
