# Generated by Django 3.0.5 on 2020-10-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20201012_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='liker',
            new_name='liked_people',
        ),
    ]
