# Generated by Django 3.0.5 on 2020-10-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20201013_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default='2020-10-15T17:03:05+09:00'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.CharField(default='2020-10-15T17:03:05+09:00', max_length=60),
        ),
    ]
