# Generated by Django 3.0.5 on 2020-10-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20201015_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
