# Generated by Django 3.0.5 on 2020-10-19 11:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20201015_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
    ]
